// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

[System.FlagsAttribute]
public enum ButtonPress : ushort
{
  A = 1,
  B = 2,
};


}
