// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ControllerInputs : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public ControllerInputs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// Bit field of ButtonPress
  public ushort Buttons { get { return __p.bb.GetUshort(__p.bb_pos + 0); } }

  public static Offset<Bwr.ControllerInputs> CreateControllerInputs(FlatBufferBuilder builder, ushort Buttons) {
    builder.Prep(2, 2);
    builder.PutUshort(Buttons);
    return new Offset<Bwr.ControllerInputs>(builder.Offset);
  }
};


}
