// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Levels : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Levels GetRootAsLevels(ByteBuffer _bb) { return GetRootAsLevels(_bb, new Levels()); }
  public static Levels GetRootAsLevels(ByteBuffer _bb, Levels obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Levels __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Bwr.Level? Levels_(int j) { int o = __p.__offset(4); return o != 0 ? (Bwr.Level?)(new Bwr.Level()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LevelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Bwr.Levels> CreateLevels(FlatBufferBuilder builder,
      VectorOffset levelsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Levels.AddLevels(builder, levelsOffset);
    return Levels.EndLevels(builder);
  }

  public static void StartLevels(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLevels(FlatBufferBuilder builder, VectorOffset levelsOffset) { builder.AddOffset(0, levelsOffset.Value, 0); }
  public static VectorOffset CreateLevelsVector(FlatBufferBuilder builder, Offset<Bwr.Level>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLevelsVectorBlock(FlatBufferBuilder builder, Offset<Bwr.Level>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartLevelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Bwr.Levels> EndLevels(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // levels
    return new Offset<Bwr.Levels>(o);
  }
}


}
