// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

public enum SettingType : byte
{
  BELT_RIGHT_SIDE = 0,
  IS_INVERTED = 1,
  IS_RIGHT_HANDED = 2,
  JOY_SENSITIVITY = 3,
  LOCO_CURVE = 4,
  LOCO_DEGREES_PER_SNAP = 5,
  LOCO_DIRECTION = 6,
  LOCO_SNAP_DEGREES_PER_FRAME = 7,
  OFFSET_FLOOR = 8,
  OFFSET_SITTING = 9,
  PHYSICS_UPDATE_RATE = 10,
  PLAYER_HEIGHT = 11,
  SNAP_ENABLED = 12,
  STANDING = 13,
  VIRTUAL_CROUCHING = 14,
};


}
