/*
struct SLZ_Marrow_Input_XRController_Fields : SLZ_Marrow_Input_XRDevice_Fields {
	int32_t _Type_k__BackingField;
	struct UnityEngine_Vector2_o _Joystick2DAxis_k__BackingField;
	bool _JoystickButton_k__BackingField;
	bool _JoystickButtonUp_k__BackingField;
	bool _JoystickButtonDown_k__BackingField;
	bool _JoystickTouch_k__BackingField;
	struct UnityEngine_Vector2_o _Touchpad2DAxis_k__BackingField;
	bool _TouchpadButton_k__BackingField;
	bool _TouchpadButtonUp_k__BackingField;
	bool _TouchpadButtonDown_k__BackingField;
	bool _TouchpadTouch_k__BackingField;
	float _Trigger_k__BackingField;
	bool _TriggerButton_k__BackingField;
	bool _TriggerButtonUp_k__BackingField;
	bool _TriggerButtonDown_k__BackingField;
	bool _TriggerTouched_k__BackingField;
	bool _GripButton_k__BackingField;
	bool _GripButtonUp_k__BackingField;
	bool _GripButtonDown_k__BackingField;
	float _Grip_k__BackingField;
	float _GripForce_k__BackingField;
	float _GripVelocity_k__BackingField;
	bool _AButton_k__BackingField;
	bool _AButtonUp_k__BackingField;
	bool _AButtonDown_k__BackingField;
	bool _ATouch_k__BackingField;
	bool _BButton_k__BackingField;
	bool _BButtonUp_k__BackingField;
	bool _BButtonDown_k__BackingField;
	bool _BTouch_k__BackingField;
	bool _MenuButton_k__BackingField;
	bool _MenuButtonUp_k__BackingField;
	bool _MenuButtonDown_k__BackingField;
	float _RingFinger_k__BackingField;
	float _IndexFinger_k__BackingField;
	float _PinkyFinger_k__BackingField;
	float _MiddleFinger_k__BackingField;
	float _ThumbFinger_k__BackingField;
};
*/
