// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ItemInSlot : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public ItemInSlot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Bwr.InventorySlot Slot { get { return (Bwr.InventorySlot)__p.bb.Get(__p.bb_pos + 0); } }
  public Bwr.Item Item { get { return (Bwr.Item)__p.bb.Get(__p.bb_pos + 1); } }

  public static Offset<Bwr.ItemInSlot> CreateItemInSlot(FlatBufferBuilder builder, Bwr.InventorySlot Slot, Bwr.Item Item) {
    builder.Prep(1, 2);
    builder.PutByte((byte)Item);
    builder.PutByte((byte)Slot);
    return new Offset<Bwr.ItemInSlot>(builder.Offset);
  }
};


}
