// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PlayerPosition : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public PlayerPosition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Bwr.Transform Headset { get { return (new Bwr.Transform()).__assign(__p.bb_pos + 0, __p.bb); } }
  public Bwr.Transform ControllerLeft { get { return (new Bwr.Transform()).__assign(__p.bb_pos + 24, __p.bb); } }
  public Bwr.Transform ControllerRight { get { return (new Bwr.Transform()).__assign(__p.bb_pos + 48, __p.bb); } }

  public static Offset<Bwr.PlayerPosition> CreatePlayerPosition(FlatBufferBuilder builder, float headset_position_X, float headset_position_Y, float headset_position_Z, float headset_rotation_euler_X, float headset_rotation_euler_Y, float headset_rotation_euler_Z, float controller_left_position_X, float controller_left_position_Y, float controller_left_position_Z, float controller_left_rotation_euler_X, float controller_left_rotation_euler_Y, float controller_left_rotation_euler_Z, float controller_right_position_X, float controller_right_position_Y, float controller_right_position_Z, float controller_right_rotation_euler_X, float controller_right_rotation_euler_Y, float controller_right_rotation_euler_Z) {
    builder.Prep(4, 72);
    builder.Prep(4, 24);
    builder.Prep(4, 12);
    builder.PutFloat(controller_right_rotation_euler_Z);
    builder.PutFloat(controller_right_rotation_euler_Y);
    builder.PutFloat(controller_right_rotation_euler_X);
    builder.Prep(4, 12);
    builder.PutFloat(controller_right_position_Z);
    builder.PutFloat(controller_right_position_Y);
    builder.PutFloat(controller_right_position_X);
    builder.Prep(4, 24);
    builder.Prep(4, 12);
    builder.PutFloat(controller_left_rotation_euler_Z);
    builder.PutFloat(controller_left_rotation_euler_Y);
    builder.PutFloat(controller_left_rotation_euler_X);
    builder.Prep(4, 12);
    builder.PutFloat(controller_left_position_Z);
    builder.PutFloat(controller_left_position_Y);
    builder.PutFloat(controller_left_position_X);
    builder.Prep(4, 24);
    builder.Prep(4, 12);
    builder.PutFloat(headset_rotation_euler_Z);
    builder.PutFloat(headset_rotation_euler_Y);
    builder.PutFloat(headset_rotation_euler_X);
    builder.Prep(4, 12);
    builder.PutFloat(headset_position_Z);
    builder.PutFloat(headset_position_Y);
    builder.PutFloat(headset_position_X);
    return new Offset<Bwr.PlayerPosition>(builder.Offset);
  }
};


}
