// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

public enum InventorySlot : byte
{
  LEFT_SHOULDER = 0,
  RIGHT_SHOULDER = 1,
  LEFT_UNDERARM = 2,
  RIGHT_UNDERARM = 3,
  BUTT = 4,
};


}
