// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ChangedSetting : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public ChangedSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Bwr.SettingType Type { get { return (Bwr.SettingType)__p.bb.Get(__p.bb_pos + 0); } }
  public float Value { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }

  public static Offset<Bwr.ChangedSetting> CreateChangedSetting(FlatBufferBuilder builder, Bwr.SettingType Type, float Value) {
    builder.Prep(4, 8);
    builder.PutFloat(Value);
    builder.Pad(3);
    builder.PutByte((byte)Type);
    return new Offset<Bwr.ChangedSetting>(builder.Offset);
  }
}


}
