// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

public enum GameMode : byte
{
  NONE = 0,
  SPEEDRUN = 1,
  ANY_PERCENT = 2,
  NO_MAJOR_GLITCHES = 3,
  NEWGAME_PLUS = 4,
  HUNDRED_PERCENT = 5,
  BLINDFOLDED = 6,
  GRIPLESS = 7,
  LEFT_CONTROLLER_GRIPLESS = 8,
  RIGHT_CONTROLLER_GRIPLESS = 9,
  ARMLESS = 10,
};


}
