// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Bwr
{

public enum SettingType : byte
{
  REFRESH_RATE = 0,
  BELT_RIGHT_SIDE = 1,
  IS_INVERTED = 2,
  IS_RIGHT_HANDED = 3,
  JOY_SENSITIVITY = 4,
  LOCO_CURVE = 5,
  LOCO_DEGREES_PER_SNAP = 6,
  LOCO_DIRECTION = 7,
  LOCO_SNAP_DEGREES_PER_FRAME = 8,
  OFFSET_FLOOR = 9,
  OFFSET_SITTING = 10,
  PHYSICS_UPDATE_RATE = 11,
  PLAYER_HEIGHT = 12,
  SNAP_ENABLED = 13,
  STANDING = 14,
  VIRTUAL_CROUCHING = 15,
};


}
