<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS0649</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../projects/Boneworks/BoneworksPerformance/src/Profiling/PoseHistoryTypes.cs"
      Link="PoseHistoryTypes.cs" />
  </ItemGroup>
</Project>
